version: '3.8'
services:
  wordpress:
    image: diogoalmeida78/wordpress
    ports:
      - "8080:80"
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - frontend_network
      - backend_network
  db:
    image: diogoalmeida78/mariadb
    ports:
      - "3306:3306"
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - backend_network
networks:
  frontend_network:
  backend_network:
volumes:
  db_data: